openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Z9527/ConsumerSample/1.0.0
info:
  description: This is a sample consumer API
  version: "1.0.0"
  title: Simple meme API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: memes
    description: Get Memes
paths:
  /meme:
    get:
      tags:
        - memes
      summary: get memes
      operationId: getAnotherMeme
      description: Call API to get another meme
      parameters:
        - in: query
          name: meme
          description: what kind of meme
          required: true
          schema:
            type: string
        - in: query
          name: top
          description: top text for the meme
          required: true
          schema:
            type: string
        - in: query
          name: bottom
          description: bottom text for the meem
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        '400':
          description: bad input parameter